---
deployment:
    tasks:
        - export DEPLOYPATH=/home2/litefing/repositories/litefi
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp logo.png $DEPLOYPATH
        - /bin/cp icon.jpg $DEPLOYPATH
        - /bin/cp -R assets $DEPLOYPATH
