---
deployment:
    tasks:
        - export DEPLOYPATH=/home2/username/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp logo.png $DEPLOYPATH
        - /bin/cp icon.jpg $DEPLOYPATH
        - /bin/cp -R assets $DEPLOYPATH
